#!/usr/bin/env zsh
# Install macOS apps
for x in keepassxc zen-browser hyper visual-studio-code rectangle quicklook-json webpquicklook; do brew install --cask $x; done &&
echo "------------------------\n\nInstalled apps:\n---------------\n" &&
brew list --cask -1 &&
brew tap homebrew/cask-versions
