#!/usr/bin/env zsh
# Install homebrew, then install formulae
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)";

for x in gh git fnm; do brew install $x; done;
echo "------------------------\n\nInstalled formulae:\n-------------------\n";
brew list --formulae -1;

echo "Setting up Node LTS\n";
eval "$(fnm env --use-on-cd)";
fnm install lts-latest;
fnm alias lts-latest default;
fnm use default;
echo "Installed Node Version:";
node -v;
